version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/staging
hooks:
  BeforeInstall:
    - location: scripts/update_server.sh
      runas: root
    - location: scripts/staging_setup.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy_setup.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/file_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/dumpautoload.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 100
      runas: root