version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/staging
hooks:
  BeforeInstall:
    - location: scripts/staging_setup.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy_setup.sh
      runas: ec2-user