image: php:7.3.28-cli

options:
  size: 2x

definitions:
  services:
    mysql:
      docker:
        memory: 7128
        
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
        
  steps:
    - step: &Composer
        name: Composer
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y zip git jq zlib1g-dev libpng-dev libzip-dev default-mysql-client python3-pip
          - apt-get clean 
          - docker-php-ext-install gd zip pdo mysqli pdo_mysql mbstring pcntl
          - pip3 install -U awscli
          - aws --version
          - aws s3 cp s3://kubernetes-dummy-mysql/homestead.sql .
          - mysql -h 127.0.0.1 -uhomestead -psecret homestead < homestead.sql
          - echo ${BITBUCKET_BUILD_NUMBER} > version.txt
          - ln -f -s .env.pipelines .env
          - mkdir -p bootstrap/cache storage/framework storage/framework/views storage/framework/sessions storage/framework/cache
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - echo ${AUTH_JSON} > auth.json
          - COMPOSER_MEMORY_LIMIT=-1 composer  update --no-interaction
          - rm -rf node_modules package-lock.json yarn.lock
          - php artisan migrate --seed
          - rm -rf homestead.sql vendor
          - zip -r application.zip . -x .env
        artifacts:
          - application.zip
        services:
          - mysql
          - docker
          
    - step: &Code-Deploy
        name: Code Deploy
        script:
          - apt-get upda- step: &Code-Deploy
        name: Code Deploy
        services:
          - docker
        script:
          - pipe: atlassian/aws-code-deploy:1.1.1
            variables:
              AWS_DEFAULT_REGION: $AWS_DEPLOYMENT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $AWS_APPLICATION_NAME
              S3_BUCKET: $AWS_DEPLOYMENT_BUCKET
              COMMAND: 'upload'
              ZIP_FILE: 'application.zip'
              VERSION_LABEL: 'hrms-build-${BITBUCKET_BUILD_NUMBER}'

          - pipe: atlassian/aws-code-deploy:1.1.1
            variables:
              AWS_DEFAULT_REGION: $AWS_DEPLOYMENT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $AWS_APPLICATION_NAME
              DEPLOYMENT_GROUP: $AWS_DEPLOYMENT_GROUP
              S3_BUCKET: $AWS_DEPLOYMENT_BUCKET
              COMMAND: 'deploy'
              WAIT: 'false'
              VERSION_LABEL: 'hrms-build-${BITBUCKET_BUILD_NUMBER}'
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'te && apt-get install -y zip
          - cp -R composer-build/* .
          - rm -rf composer-build
          - mkdir -p bootstrap/cache
          - mkdir -p storage/framework storage/framework/views storage/framework/sessions storage/framework/cache
          - zip -r application-multi-tenancy-v8.zip .
          - pipe: atlassian/aws-code-deploy:0.5.0
            variables:
              AWS_DEFAULT_REGION: $AWS_DEPLOYMENT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $AWS_APPLICATION_NAME
              S3_BUCKET: $AWS_DEPLOYMENT_BUCKET
              COMMAND: 'upload'
              ZIP_FILE: 'application-multi-tenancy-v8.zip'
              VERSION_LABEL: 'rms-build-${BITBUCKET_BUILD_NUMBER}'

          - pipe: atlassian/aws-code-deploy:0.5.0
            variables:
              AWS_DEFAULT_REGION: $AWS_DEPLOYMENT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $AWS_APPLICATION_NAME
              DEPLOYMENT_GROUP: $AWS_DEPLOYMENT_GROUP
              S3_BUCKET: $AWS_DEPLOYMENT_BUCKET
              COMMAND: 'deploy'
              WAIT: 'false'
              VERSION_LABEL: 'rms-build-${BITBUCKET_BUILD_NUMBER}'
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
  
pipelines:

  tags:
    v3.*.*:
      - step: *Composer
      - step: *Code-Deploy

  branches:
    code-deploy:
      - step: *Composer
      - step: *Code-Deploy
    master:
      - step: *Composer
      - step:
          <<: *Code-Deploy
          name: Code Deploy
          deployment: MultitenancyV8
    MultitenancyV8Dev:
      - step: *Composer
      - step:
          <<: *Code-Deploy
          name: Code Deploy
          deployment: MultitenancyV8Dev
