image: atlassian/default-image:2

definitions:
  services:
    docker:
      memory: 7128
  steps:
    - step: &Build-Image
        name: Build Image
        services:
          - docker
        script:
          - source ./check.sh
          - IMAGE="seamlesshr/${KUBE_META_NAME}"
          - VERSION="HRMS-${BITBUCKET_BUILD_NUMBER}"
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          # - sh [[ ! -z "${BITBUCKET_TAG}" ]] && export IMAGE_BRANCH="${BITBUCKET_TAG}" || export IMAGE_BRANCH="${BITBUCKET_BRANCH}"
          - docker build -t ${IMAGE} --build-arg SECRETHUB_CREDENTIAL=${SECRETHUB_CRED} --build-arg IMAGE_TAG={BITBUCKET_BRANCH} .
          - docker tag ${IMAGE} ${IMAGE}:${VERSION}
          - docker push ${IMAGE}
          - envsubst < deployment.tpl.yaml > deployment-${KUBE_META_NAME}.yaml
          - mkdir -p s3/products && cp deployment-${KUBE_META_NAME}.yaml s3/products/deployment-${KUBE_META_NAME}.yaml
          - pipe: atlassian/aws-s3-deploy:0.4.5
            variables:
              S3_BUCKET: 'seamlesshrms-kubernetes-deployments'
              LOCAL_PATH: 's3'
              EXTRA_ARGS: '--metadata image-tag="${IMAGE}:${VERSION}"'
          - pipe: atlassian/aws-eks-kubectl-run:1.2.0
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_KUBERNETES}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_KUBERNETES}
              AWS_DEFAULT_REGION: "us-east-1"
              CLUSTER_NAME: ${AWS_CLUSTER_NAME_KUBERNETES}
              KUBECTL_COMMAND: "apply"
              RESOURCE_PATH: "deployment-${KUBE_META_NAME}.yaml"
              DEBUG: "true"
              KUBECTL_ARGS:
                - "--dry-run"
          - pipe: atlassian/aws-eks-kubectl-run:1.2.0
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_KUBERNETES}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_KUBERNETES}
              AWS_DEFAULT_REGION: "us-east-1"
              CLUSTER_NAME: ${AWS_CLUSTER_NAME_KUBERNETES}
              KUBECTL_COMMAND: "apply"
              RESOURCE_PATH: "deployment-${KUBE_META_NAME}.yaml"
              DEBUG: "true"



options:
  size: 2x

pipelines:

  branches:
    v2-kubernetes:
      - step: 
          <<: *Build-Image
          name: Build-Image
          deployment: rms-kubernetes
        services:
          - docker
    non-recurring-dev-rms:
      - step: 
          <<: *Build-Image
          name: Build-Image
          deployment: non-recurring-dev-rms
        services:
          - docker
    non-recurring-qa-rms:
      - step: 
          <<: *Build-Image
          name: Build-Image
          deployment: non-recurring-qa-rms
        services:
          - docker
    non-recurring-uat-rms:
      - step: 
          <<: *Build-Image
          name: Build-Image
          deployment: non-recurring-dev-rms
        services:
          - docker